// src/MyApp.jsx

import React, { useState, useEffect } from "react";
import Table from "./Table";
import Form from "./Form";

function MyApp() {
  const [characters, setCharacters] = useState([]); // empty state

  function removeOneCharacter(index) {
    const updated = characters.filter((character, i) => {
      return i !== index;
    });
    setCharacters(updated);
  }

  function updateList(person) {
    setCharacters([...characters, person]); // '...' -> ES6 spread operator
  }

  // fucntion to fetch users directly from the backend using Express APIs
  // returns promise to perform operation that takes time, basics of asynchronous processing
  // promise generated by fetch()
  function fetchUsers() {
    const promise = fetch("http://localhost:8000/users");
    return promise;
  }

  // functional component to call fetchUsers()
  // .then() is used for when promise is fulfilled, setting component state using setCharacters
  // res.json() used to parse response of promise from JSON format to JavaScript object
  useEffect(() => {
    fetchUsers()
      .then((res) => res.json())
      .then((json) => setCharacters(json["users_list"]))
      .catch((error) => {
        console.log(error);
      });
  }, []);

  return (
   <div className ="container">
    <Table 
      characterData={characters}
      removeCharacter={removeOneCharacter} 
    />
    <Form handleSubmit={updateList} />
   </div>
  );
}

export default MyApp;
